export interface Spacecraft  {
    id:number,
    name:'string',
    img: 'string',
    price: number,
    manufacturer:'string',
    launch_date:'string',
    mission_duration:number,
    crew_capacity:number,
    payload_capacity:number,
    propellant_type:'string',
    thrust:number,
    orbit_type:'string',
    quantity: number,
}